### ISSUE TITLE
Unable to go-get github.com/divan/whispervis

### ISSUE THREAD

**Issue by mewmew** [divan/whispervis#1]
Hi Ivan,

Thank you for a really wonderful Go Advent post. I think you may have re-ignited a spark in me for trying to write front-ends that had long since lost its ember.

I really wanted to try to play around with your visualization demo locally, and thus tried to go-get the whisperviz project. However, it failed with the following error:

```
$ go get -u github.com/divan/whispervis/...
# cd .; git clone https://github.com/divan/simulation /home/u/goget/src/github.com/divan/simulation
Cloning into '/home/u/goget/src/github.com/divan/simulation'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/divan/whispervis
	imports github.com/divan/simulation/propagation: exit status 128
package github.com/divan/whispervis
	imports github.com/divan/simulation/stats: cannot find package "github.com/divan/simulation/stats" in any of:
	/home/u/go1.12/src/github.com/divan/simulation/stats (from $GOROOT)
	/home/u/goget/src/github.com/divan/simulation/stats (from $GOPATH)
	/home/u/Desktop/go/src/github.com/divan/simulation/stats
```

Seems like the `go get` is unable to locate the github.com/divan/simulation repo.

Wish you all the best and send happy winter wishes from Sweden :)

/u

**Comment by divan** [comment]
Oh my. Sorry for that, as I was mostly playing working with this for myself, and changed import paths a bit, I forgot to make it public. Fixed now: https://github.com/divan/simulation

**Comment by mewmew** [comment]
Hi Ivan,

Thanks for releasing the project :) It works great now.

![2018-12-21-230649_1662x1009_scrot](https://user-images.githubusercontent.com/1414531/50365499-303b0e80-0575-11e9-8ef0-d293b5949b1a.png)

You may want to add a note to the readme of how to run the simulation server, e.g.

> To visualize simulations, first install the simulation server
>
> `$ go get -u github.com/divan/simulation/cmd/propagation_server`
>
> Then start the simulation server, which listens on port 8084 by default.
>
> `$ propagation_server`

**Comment by P31N** [comment]
How did you make it work - unable to make it run

**Comment by mewmew** [comment]
Hi @P31N,

This was quite some time ago, so don't remember : ) Still, really cool project! Wish you the best in coding.

Cheers,
Robin

**Comment by P31N** [comment]
All good thanks for the reply
